# Generated by Django 4.2.3 on 2023-08-02 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zyboapp', '0003_departmentmodel_doctormodel_appointmentsmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departmentmodel',
            old_name='name',
            new_name='department',
        ),
    ]
