# Generated by Django 4.2.3 on 2023-08-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zyboapp', '0006_alter_appointmentsmodel_status_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctormodel',
            name='photo',
            field=models.ImageField(upload_to='zyboapp/static/doctors'),
        ),
    ]
