# Generated by Django 4.2.3 on 2023-08-04 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zyboapp', '0007_alter_doctormodel_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentsmodel',
            name='status',
        ),
    ]
