# Generated by Django 4.2.3 on 2023-08-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zyboapp', '0008_remove_appointmentsmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentsmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
