# Generated by Django 4.2.3 on 2023-08-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zyboapp', '0009_appointmentsmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentsmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
